apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  name: fluentd-only-stdout
  namespace: fluent
  labels:
    output.fluentd.fluent.io/mode: "fluentd-only"
    output.fluentd.fluent.io/enabled: "true"
spec:
  outputs:
    - stdout: {}